# ./inventories/group_vars/docker_hosts.yml

docker_data_root: /home/admin
immich_compose_dir: /home/admin/immich

nfs_mount_base: /mnt/nfs
nfs_mounts:
  - name: images
    src: "{{ nfs_server_ip }}:/mnt/atl/images"
    path: "{{ nfs_mount_base }}/images"
    opts: "ro,nfsvers=4,soft"
  - name: immich
    src: "{{ nfs_server_ip }}:/mnt/atl/immich"
    path: "{{ nfs_mount_base }}/immich"
    opts: "rw,nfsvers=4,soft"