# ./inventories/hosts.yml

all:
  children:
    truenas:
      hosts:
        lala110:
          ansible_host: 10.0.0.110
          ansible_connection: local

    docker_hosts:
      hosts:
        docker01:
          ansible_host: 10.0.0.115
          ansible_user: ansible
          ansible_become: true
